version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - aws --version
      - chmod +x deploy.sh
  build:
    commands:
      - ./deploy.sh

artifacts:
  files:
    - '**/*'
